### ISSUE TITLE
有關comment的問題

### ISSUE THREAD

**Issue by alex85279** [Compiler-s22/Discussion#10]
助教您好，我對comment的實作上有一個問題
根據測資
/* ...
........
........*/
//comment
將不會印出任何東西這件事情(包括第三行的\n)，我們是否應理解為*/的同一行內即使有任何字元也不會print出來，
例如
/* ...
........
........*/ a = b;
//comment
是否要print出a = b的source呢?

十分感謝助教

**Comment by LittleLaGi** [comment]
同學你好:
> 將不會印出任何東西這件事情...

是否要印出 source 是由 `//&S+` 和 `//&S-` 決定的，和 comment 沒有關係，
所以是否要印出 `a = b` 要看當時的 pseudocomments S 是開啟的還是關閉的。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by alex85279** [comment]
助教不好意思，針對同一個測資我有一個新的問題想要詢問您
