### ISSUE TITLE
<INITIAL> 是否可以省略？

### ISSUE THREAD

**Issue by Luke2336** [Compiler-s22/Discussion#11]
## test case
```
/*
comment
*/
```

## code
```c++
%{
#include<stdio.h>
%}

letter [A-Za-z]
digit [0-9]
%S COMMENT

%%

<COMMENT>[^*\n] {}
<COMMENT>"*/" { BEGIN INITIAL; }
<COMMENT>"*" {}
<COMMENT>"\n" {}
"/*" { BEGIN COMMENT; }
<INITIAL>{letter}({letter}|{digit})* { printf("identifier\n"); }

%%
```

請問 `<INITIAL>{letter}({letter}|{digit})*` 的 `<INITIAL>` 是否可以省略？
假設可以的話，爲什麼以上的 code 拿掉 `<INITIAL>` 後會印出 `identifier`？

**Comment by Luke2336** [comment]
```c++
%{
#include<stdio.h>
%}

letter [A-Za-z]
digit [0-9]
%S COMMENT

%%

<COMMENT>[^*\n] {}
<COMMENT>"*/" { BEGIN INITIAL; }
<COMMENT>"*" {}
<COMMENT>. {}
<COMMENT>"\n" {}
"/*" { BEGIN COMMENT; }
{letter}({letter}|{digit})* { printf("identifier\n"); }

%%
```

謝謝助教的回應。
但我改成以上的 code 後，同樣會印出 `identifier`，且編譯時會出現 `init.l:14: warning, rule cannot be matched`。

**Comment by LittleLaGi** [comment]
同學你好:

> ... 同樣會印出 identifier ...

要把 `%s` 改成 `%x`，原因可以參考 #12。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by LittleLaGi** [comment]
對了，你這邊不需要 `<COMMENT>. {}`，所有 pattern 都有 match 到了，之前沒注意到。
