### ISSUE TITLE
%s 和 %x 的差別？

### ISSUE THREAD

**Issue by Luke2336** [Compiler-s22/Discussion#12]
想請問能不能給出一些例子說明 `%s` 和 `%x` 在使用上的差別？

有查到 document 中這一段有寫兩者是不一樣的：[https://github.com/westes/flex/blob/master/doc/flex.texi#L1676-L1692](https://github.com/westes/flex/blob/master/doc/flex.texi#L1676-L1692)

**Comment by LittleLaGi** [comment]
同學你好:

可以參考[這篇文章](https://www.cs.virginia.edu/~cr4bd/flex-manual/Start-Conditions.html):
> If the start condition is inclusive, then rules with no start conditions at all will also be active. If it is exclusive, then only rules qualified with the start condition will be active.

也就是說如果使用 inclusive start condition (%s)，那 `<INITIAL>` 也會被納入候選。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
