### ISSUE TITLE
C++

### ISSUE THREAD

**Issue by why527** [Compiler-s22/Discussion#13]
請問可以使用c++library在lex file裡嗎？比如<string><vector>

**Comment by LittleLaGi** [comment]
同學你好:
可以哦，作業三就會需要用到，但 C++ 的部分主要會用在 parser。 

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
