### ISSUE TITLE
scientific

### ISSUE THREAD

**Issue by why527** [Compiler-s22/Discussion#14]
請問如果是3E9會表示成3.0E9還是3E9，又或者兩個狀況都必須要處理呢？

**Comment by LittleLaGi** [comment]
同學你好:

依據作業說明，Scientific Notations 的 coefficient 可以是 a nonzero integer or a nonzero floating-point decimal number。
因為 `3.0` 在我們的作業中是合法的 Floating-Point Constants，因此兩種情況都需要處理哦  

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
