### ISSUE TITLE
string constant

### ISSUE THREAD

**Issue by why527** [Compiler-s22/Discussion#15]
想請問如何處理""，比如input是aa"bb" 那我的output應該是啥

**Comment by LittleLaGi** [comment]
同學你好:

應該要辨識出 identifier `aa` 和 string `"bb"`，
至於具體的輸出的話可以參考 test 資料夾裡的內容，測資和答案都在裡面。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
