### ISSUE TITLE
about whitespace

### ISSUE THREAD

**Issue by why527** [Compiler-s22/Discussion#16]
如果我想表示"mod "，貌似會出現unrecognized rule，是不是應該表示成"mod"\t，還是我的理解有誤！

**Comment by LittleLaGi** [comment]
同學你好:

你 "mod" 指的是 string 嗎?
出現 unrecognized rule 這個 error 可能是你的 regular expression 有寫錯 (語法錯誤)，
可以檢查一下 string 那邊的 regular expression。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by why527** [comment]
對的，"mod" 指的是 string ，請問"mod "和"mod"\t 分別是可行的嗎？

**Comment by LittleLaGi** [comment]
啊，你是說你單純想 match "mod" 這個 pattern 嗎? 我本來以為是你要拿來當測資的。
照理來說直接 "mod" 右邊放 action 就可以了，你其他的 pattern 有遇到類似的問題嗎?

**Comment by why527** [comment]
我想match"mod"加一格空格，所以想問在regular expression裡，"mod "和"mod"\t分別是可行的嗎？

**Comment by LittleLaGi** [comment]
> "mod "

這樣寫是可以的哦，也可以寫成 mod[ ]

**Comment by why527** [comment]
了解！那可以請問
"mod "{TOKEN("mod"); }
":= " {TOKEN(":="); } 在語法上有甚麼錯誤嗎？執行了 lex scanner.l一直顯示這兩行有出現unrecognized rule，
![螢幕擷取畫面 (185)](https://user-images.githubusercontent.com/99729882/158867525-823282af-5776-4ab8-bca6-67174c0e38a0.png)

**Comment by LittleLaGi** [comment]
> "mod "{TOKEN("mod"); }

這個應該是因為你沒有空格，左邊的 pattern 跟右邊的 action 中間至少要有一個空格。

> ":= " {TOKEN(":="); }

這個看起來沒什麼問題，不然你先改好上面的，說不定就沒問題了。
