### ISSUE TITLE
只讀到第一行

### ISSUE THREAD

**Issue by why527** [Compiler-s22/Discussion#17]
我目前的檔案都只能讀到測資第一行，但是讀寫是正確的，請問我是不是忽略了甚麼？我只有動transition rule 的部分，definition part應該也不影響，目前比較懷疑的是yylex()是不是只能讀一行？

**Comment by LittleLaGi** [comment]
同學你好:
是指讀一行，output 都正確，也沒有報錯?

**Comment by why527** [comment]
是的 他只有output出第一個token比如<KWvar>

**Comment by LittleLaGi** [comment]
lex 的機制是一個字元一個字元讀進來，然後依照你定義的 pattern 去做 matching，基本上就像老師上課講到的狀態機。
會不會是換行的部分寫錯了?
