### ISSUE TITLE
About ../sample_solutions/2_declaration

### ISSUE THREAD

**Issue by Luke2336** [Compiler-s22/Discussion#30]
I think line 21 should be correct from `-1.000000` to `-1.0`.

```
       constant <line: 14, col: 10> -1.000000
```

```
       constant <line: 14, col: 10> -1.0
```

**Comment by LittleLaGi** [comment]
同學你好:

為了方便實作，浮點數統一印到小數點後第六位 (printf, cout 預設就是六位)。
實際編譯完執行的時候一樣會有精度問題，所以在印 AST 的時候不需要特別要求要跟當初讀到的位數一樣。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by Luke2336** [comment]
@LittleLaGi

助教您好，
請問科學符號的印法是如何？
是前面浮點數的部分取成小數點後六位，還是直接當成浮點數輸出呢？

**Comment by LittleLaGi** [comment]
讀進來的時候直接存成 float 或 double 就可以，不用特別分。
