### ISSUE TITLE
Final exam on June 7

### ISSUE THREAD

**Issue by ypyou** [Compiler-s22/Discussion#37]
Hello, @Compiler-s22/students,

The final exam will be held next Tuesday. However, according to the NYCU epidemic prevention measures, the exam will not be held in the physical classroom. It will be a take-home exam, but you will still need to return your answers by the end of the exam time.

Here are the exam details.

Time: 10:10-12:00 on June 7
Scope: Chapters 5, 6 ,and 7 (Sections 7.1-7.2)
Notice: The exam questions will be released on E3 at 10:10, June 7, and you will need to take **CLEAR** photos of your answers and submit them on E3 by 12:00, June 7. **NO LATE SUBMISSION IS ALLOWED**, so please reserve some time (say 10 minutes) for the submission process. If you have any questions regarding the exam questions, I'll be in the Webex meeting room during the exam to answer your questions.

**Comment by PersonalWorkingSpace** [comment]
Does this mean it is a open-book exam?

**Comment by ypyou** [comment]
> Does this mean it is a open-book exam?

Yes

**Comment by weii41392** [comment]
> Time: 10:10-12:00 on June 7

I believe the time slot should be 13:20 - 15:10?

**Comment by ypyou** [comment]
> > Time: 10:10-12:00 on June 7
> 
> I believe the time slot should be 13:20 - 15:10?

That's right. I made it wrong. The exam time should be 13:20-15:10 on June 7.
