### ISSUE TITLE
練習問問題

### ISSUE THREAD

**Issue by why527** [Compiler-s22/Discussion#5]
![螢幕擷取畫面 (182)](https://user-images.githubusercontent.com/99729882/155487407-a0948b72-4e29-4616-84de-c4b31873c3a9.png)
請問我 make docker-pull完後，docker image ls | grep hw0，發現我 latest右邊一欄跟網站範例不同(如圖)，請問是正常的嗎？

**Comment by LittleLaGi** [comment]
同學你好，
這個不影響，進 docker 以後環境能正常運作就好。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
