### ISSUE TITLE
github repo

### ISSUE THREAD

**Issue by why527** [Compiler-s22/Discussion#6]
請問github repo是 repositories的意思嗎？ 我在sudo git push後，顯示Everything up-to-date後，並沒有發現我的repositories有更新，請問這樣是正常的嗎？

**Comment by LittleLaGi** [comment]
同學你好：
> 請問github repo是 repositories的意思嗎？

是的。

> 我在sudo git push後 ...

有成功 push 上去哦，在[這裡](https://github.com/Compiler-s22/hw0-why527)。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
