### ISSUE TITLE
關於docker的問題

### ISSUE THREAD

**Issue by alex85279** [Compiler-s22/Discussion#7]
助教您好，我使用WSL2的Ubuntu 18.04進行hw0，
在遵循Readme進行到./activate_docker.sh時，得到了如附圖的error訊息。
由於瀏覽後沒有看到有類似的問題，因此想請問助教是否給予一些幫助。
十分感謝助教

![image](https://user-images.githubusercontent.com/21103268/155876642-5fbbdede-7d0c-47c8-b54f-5608b1c1bf23.png)

![image](https://user-images.githubusercontent.com/21103268/155876619-759e9a6e-ef63-41e7-97cd-c2b40db42435.png)

**Comment by LittleLaGi** [comment]
同學你好:
執行某些 docker 的功能會需要管理者的權限 (可以從 `permission denied` 這個錯誤訊息得知)，
要改成:  `sudo ./activate_docker.sh`。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by alex85279** [comment]
助教您好，
截圖中的內容是我已經調整過權限的部分，因此圖中的操作已經擁有管理者權限。
一開始在權限不足的情況下我沒加上sudo所得到的error code僅為permission denied，而沒有unknown的這項註解。

另外，我剛剛已經嘗試過使用虛擬機，並以完全相同的步驟進行操作，結果是沒問題的。

**Comment by LittleLaGi** [comment]
你好，WSL2 有時候會有問題，這個部分我們也不確定原因，
你先用虛擬機好了，謝謝!

**Comment by alex85279** [comment]
好的，十分感謝助教
