### ISSUE TITLE
Why is 00123.123 invalid?

### ISSUE THREAD

**Issue by Luke2336** [Compiler-s22/Discussion#9]
Why can't `00123.123` be recognized as two part? (`00` and `123.123`) 

I found this problem in `test/advance_cases/sample_solutions/9_float`.

**Comment by LittleLaGi** [comment]
同學你好:
我們會把符合規定的的符號全部吃進來，所以依據 `octal integer` 的定義，會算到 `.` 之前。
不這樣的話會出現許多模稜兩可的情況，比如說，如果能隨意拆開的話，
`00123.123` 可以拆成 `00` 和 `123.123`，也可以拆成 `0` 和 `0` 和 `123.123` (還有很多種可能性)。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by weii41392** [comment]
@LittleLaGi 請問助教，

> 同學你好: 我們會把符合規定的的符號全部吃進來，所以依據 `octal integer` 的定義，會算到 `.` 之前。

如果以這邊的解釋而言，是不是 `009.1` 這種 input 也應該是 invalid？因為會 match 到 `009`，而後面的 `.1` 則無法 match。另外如果考慮到 programming language 的 convention，是否也不應該出現 constant - constant 相連的情況？

**Comment by LittleLaGi** [comment]
同學你好:

> 如果以這邊的解釋而言，是不是 009.1 這種 input 也應該是 invalid？

0 開頭會被視為是八進位的數字，到 9 時因為 >= 8，所以會停止。00123 因為都是八進位的數字所以才會全部 match 完。

> 另外如果考慮到 programming language 的 convention，是否也不應該出現 constant - constant 相連的情況？

確實一般不會遇到 constant - constant 相連的情況，這個作業會有這樣的測資主要是要讓同學了解 pattern matching 的機制。
另外，以後如果有需要基於其它的 issue 提問，可以建一個新的 issue，並標註你想參考的 issue (`#` + issue 號碼)，這樣會比較容易追蹤問題是否已經被解決了，謝謝。
